export const LOAD_POSTS = 'LOAD_POSTS';
export const REMOVE_POST = 'REMOVE_POST';
export const ADD_POST = 'ADD_POST';
export const SEARCH_POST = 'SEARCH_POST';
export const SEARCH_POST_BY_STATUS = 'SEARCH_POST_BY_STATUS';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const RESOLVE_POST = 'RESOLVE_POSTS';
export const SORT_POSTS_BY_STATUS = 'SORT_POSTS_BY_STATUS';
